# This image is meant to enable cross-architecture builds.
# It assumes the ream binary has already been
# compiled for `$TARGETPLATFORM` and moved to `./dist/bin/$TARGETARCH`.
FROM ubuntu:24.04

LABEL org.opencontainers.image.source=https://github.com/reamlabs/ream
LABEL org.opencontainers.image.description="Ream is a modular, open-source Ethereum Beam Chain client."
LABEL org.opencontainers.image.licenses="MIT"

ARG GIT_COMMIT
ARG GIT_BRANCH
ARG BUILD_DATE

LABEL org.opencontainers.image.revision=$GIT_COMMIT
LABEL org.opencontainers.image.created=$BUILD_DATE
LABEL org.opencontainers.image.version=$GIT_BRANCH

# Filled by docker buildx
ARG TARGETARCH

COPY ./dist/bin/$TARGETARCH/ream /usr/local/bin/ream

EXPOSE 9000/udp 5052 8080
ENTRYPOINT ["/usr/local/bin/ream"]
