[package]
name = "ream-rpc-data-availability"
authors.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
default = []

[dependencies]
actix-web.workspace = true
alloy-primitives.workspace = true
ream-api-types-common.workspace = true
ream-data-availability.workspace = true
ream-data-availability-node.workspace = true
ream-rpc-common.workspace = true
serde.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
