[package]
name = "ream"
description = "A Rust implementation of the Ethereum Beam Chain specification."
authors.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[[bin]]
name = "ream"
path = "src/main.rs"

[dependencies]
alloy-primitives.workspace = true
anyhow.workspace = true
bip32.workspace = true
clap = { workspace = true, features = ["derive", "env"] }
discv5.workspace = true
hashbrown.workspace = true
rand.workspace = true
tokio.workspace = true
tracing = { workspace = true, features = ["log"] }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
unicode-normalization.workspace = true
url.workspace = true

# ream dependencies
ream-account-manager.workspace = true
ream-beacon-api-types.workspace = true
ream-checkpoint-sync.workspace = true
ream-consensus.workspace = true
ream-discv5.workspace = true
ream-executor.workspace = true 
ream-keystore.workspace = true
ream-network-manager.workspace = true
ream-network-spec.workspace = true 
ream-node.workspace = true
ream-operation-pool.workspace = true
ream-p2p.workspace = true 
ream-rpc.workspace = true
ream-storage.workspace = true
ream-validator.workspace = true
