name: Nightly

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  slow-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Run slow tests (generate_key_pair)
        run: cargo test --release --workspace -- --ignored --nocapture

  slow-tests-devnet3:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Run slow tests devnet3
        run: cargo test --release --workspace --no-default-features --features "devnet3" -- --ignored --nocapture --test-threads=1
